# Generated by Django 5.1 on 2024-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('instituicao', models.CharField(max_length=120)),
                ('plataforma', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to='cursos/')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('is_learning', models.BooleanField()),
                ('descricao', models.TextField()),
                ('pic', models.ImageField(upload_to='skills/')),
            ],
        ),
    ]
