# Generated by Django 5.1 on 2024-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.CharField(default='professor_nulo', max_length=100),
            preserve_default=False,
        ),
    ]
