# Generated by Django 5.1 on 2024-08-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_curso_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='is_learning',
        ),
        migrations.AddField(
            model_name='curso',
            name='is_learning',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
